Rename module for consistency, add Canceler
purescript-contrib/purescript-fork pull request #1
Opened 2016-11-21 16:34 UTC by garyb

2016-11-21 19:00 UTC, natefaubion requested changes

2016-11-21 19:00 UTC, natefaubion commented on src/Control/Monad/Fork/Canceler.purs
> +newtype Canceler m = Canceler (Error → m Boolean)
This doesn't work because the Error is abstract in MonadFork. Should be `Canceler e m`.

2016-11-21 19:43 UTC, garyb commented on src/Control/Monad/Fork/Canceler.purs
> +newtype Canceler m = Canceler (Error → m Boolean)
Excellent point.

2016-11-21 20:47 UTC, natefaubion commented on src/Control/Monad/Fork/Class.purs
> +    pure \reason → Aff.cancel ac reason
I think this can be `Aff.cancel <$> Aff.forkAff aff`

2016-11-21 20:48 UTC, natefaubion commented on src/Control/Monad/Fork/Class.purs
> +    pure \reason → Aff.cancel ac reason
`map Aff.cancel <<< Aff.forkAff` 👀

2016-11-22 03:55 UTC, natefaubion approved these changes

2016-11-22 12:12 UTC, merged